version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  build:
    commands:
      - yarn install
      - yarn build

  post_build:
    commands:
      - VERSION=$(node -p -e "require('./package.json').version")
      - aws s3 sync ./.build s3://cdn.squeaky.ai/g/$VERSION
      - aws cloudfront create-invalidation --distribution-id E2DF5UJN3IYB51 --paths "/g/$VERSION/*"

cache:
  paths:
    - node_modules/**/*
