version: 0.2

phases:
  pre_build:
    commands:
      - mkdir -p /usr/local/lib/nodejs
      - wget https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-arm64.tar.xz
      - tar -xJvf node-v18.12.1-linux-arm64.tar.xz -C /usr/local/lib/nodejs
      - export PATH=/usr/local/lib/nodejs/node-v18.12.1-linux-arm64/bin:$PATH

  build:
    commands:
      - yarn install
      - yarn build

  post_build:
    commands:
      - VERSION=$(node -p -e "require('./package.json').version")
      - aws s3 sync ./.build s3://cdn.squeaky.ai/g/$VERSION
      - aws cloudfront create-invalidation --distribution-id E2DF5UJN3IYB51 --paths "/g/$VERSION/*"

cache:
  paths:
    - node_modules/**/*
